@baseUrl = http://127.0.0.1:8000

# @name home
GET {{baseUrl}}

@accessToken = Bearer {{login.response.body.bearer.access}}

###
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "evil",
  "email": "evil@test.com",
  "password": "123456",
  "firstName": "Evil",
  "lastName": "User",
}


###
# @name login
post {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "musa@test.com",
    "password": "123456"
}

### 

# @name logout
post {{baseUrl}}/auth/logout
Authorization: {{accessToken}}

### 
# @name refresh
post {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2YTFjYzVjYzQ4YTRiNDE0ZWZhZTVmNTEiLCJpYXQiOjE3ODAyODEyOTIsImV4cCI6MTc4MDM2NzY5Mn0.pmxGcuVpdy8xDFCfzGvJPZtLD9tRmr-XqVeJC3aXajI"
}


###
# @name userList

get {{baseUrl}}/users/
Authorization: {{accessToken}}

###
# @name userRead
get {{baseUrl}}/users/6a1cc54d48a4b414efae5f50

###
# @name userCreate
post {{baseUrl}}/users
Content-Type: application/json

{
    "username": "admin2",
    "password": "1234",
    "email": "admin2@test.com",
    "firstName": "admin",
    "lastName": "admin",
    "isActive": true,
    "isAdmin": true
}


###
# @name userUpdate
put {{baseUrl}}/users/6a1cc54d48a4b414efae5f50
Content-Type: application/json

{
    "isAdmin": false
}

###
# @name userDelete
delete {{baseUrl}}/users/6a1cc54d48a4b414efae5f50

###
# @name carList
GET {{baseUrl}}/cars
Authorization: {{accessToken}}

###
# @name carAvailableList
GET {{baseUrl}}/cars/available?startDate=2026-07-01&endDate=2026-07-05&filter[brand]=Mercedes
Authorization: {{accessToken}}

###
# @name createCar
POST {{baseUrl}}/cars
Authorization: {{accessToken}}
Content-Type: application/json

{
    "plateNumber": "PF-PP-116",
    "brand": "Fiat",
    "model": "Egea",
    "year": 2019,
    "isAutomatic": false,
    "pricePerDay": 38
  }

###
# @name carRead
get {{baseUrl}}/cars/6a1e88911ee8044bbd0bbb8f


###
# @name carUpdate
put {{baseUrl}}/cars/6a1e88911ee8044bbd0bbb8f
Content-Type: application/json

{
  "pricePerDay": 100
}

###
# @name carDelete
delete {{baseUrl}}/cars/6a1d2dbb040a876fbc695f30
Authorization: {{accessToken}


###
# @name reservationList
GET {{baseUrl}}/reservations
Authorization: {{accessToken}}



###
# @name createReservation
POST {{baseUrl}}/reservations
Authorization: {{accessToken}}
Content-Type: application/json

{
  "carId": "6a1ec8f2176c194d588ede48",
  "startDate": "2026-07-01",
  "endDate": "2026-07-05"
}

###
# @name reservationRead
get {{baseUrl}}/reservations/6a1f518201d57fbc2376cb83
Authorization: {{accessToken}}


###
# @name reservationUpdate
put {{baseUrl}}/reservations/6a1e88911ee8044bbd0bbb8f
Authorization: {{accessToken}}
Content-Type: application/json

{
  "startDate": "2023-10-01",
  "endDate": "2023-10-10"
}

###
# @name reservationDelete
delete {{baseUrl}}/reservations/6a1d2dbb040a876fbc695f30
Authorization: {{accessToken}}




